### ISSUE TITLE
Lib version management

### ISSUE THREAD

**Issue by canhlinh** [qor/render#4]
Please use `Glide` or anything to manage library version for the whole of QOR.
I fetched the latest version of `github.com/qor/render` and `github.com/qor/qor` but still missing files.
<img width="495" alt="screen shot 2017-09-21 at 20 11 39" src="https://user-images.githubusercontent.com/2246996/30697420-20b63918-9f09-11e7-917e-f974d0ea56ab.png">

**Comment by jinzhu** [comment]
Hi @canhlinh 

I think you are not using latest `qor/qor`, but we do are looking for a version management, maybe using `pak`

**Comment by canhlinh** [comment]
@jinzhu You are right. I'm not using the latest version.
I've updated all the hash of the `qor` libs for `Glide`. Everything work well.

**Comment by jinzhu** [comment]
cool, glad it works
